version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: automation_ai_password
      MYSQL_DATABASE: automation_ai_db
      MYSQL_USER: automation_ai_user
      MYSQL_PASSWORD: automation_ai_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # Redis for Celery
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  # Django Backend
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-change-this-in-production
      - DB_NAME=automation_ai_db
      - DB_USER=automation_ai_user
      - DB_PASSWORD=automation_ai_password
      - DB_HOST=db
      - DB_PORT=3306
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  # Celery Worker
  celery:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-change-this-in-production
      - DB_NAME=automation_ai_db
      - DB_USER=automation_ai_user
      - DB_PASSWORD=automation_ai_password
      - DB_HOST=db
      - DB_PORT=3306
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    command: celery -A automation_ai worker -l info

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mysql_data:
