# Generated by Django 4.2.7 on 2025-08-17 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('default_repetitiveness', models.IntegerField(default=3)),
                ('default_rule_based', models.IntegerField(default=3)),
                ('default_complexity', models.IntegerField(default=3)),
                ('default_volume', models.IntegerField(default=3)),
                ('default_standardization', models.IntegerField(default=3)),
                ('default_current_errors', models.IntegerField(default=3)),
                ('guidance_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=200)),
                ('current_score', models.IntegerField()),
                ('recommended_improvements', models.TextField()),
                ('estimated_impact', models.TextField()),
                ('implementation_steps', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
